# Generated by Django 4.0.3 on 2022-03-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='complexity',
            field=models.CharField(choices=[(1, 'hard'), (2, 'normal'), (3, 'easy')], max_length=250),
        ),
    ]
