# Generated by Django 4.0.3 on 2022-03-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_sphere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='complexity',
            field=models.PositiveIntegerField(choices=[(1, 'hard'), (2, 'normal'), (3, 'easy')]),
        ),
    ]
