# Generated by Django 4.0.3 on 2022-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sphere',
            field=models.ManyToManyField(blank=True, null=True, to='tests.sphere'),
        ),
    ]
