# Generated by Django 4.0.3 on 2022-03-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_test_sphere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sphere',
            field=models.ManyToManyField(blank=True, to='tests.sphere'),
        ),
    ]
